# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1exPIAoxrxptmarYExiXXUwR_ku4jtJ7K
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

print("[INFO] Đang khởi tạo Dataset tuân theo tiêu chuẩn nhân trắc học Ngũ Hành...")

num_samples = 250  # 250 ảnh chia đều cho 5 hệ (mỗi hệ 50 ảnh)
img_width, img_height = 128, 128
num_classes = 5

X_data = np.zeros((num_samples, img_width, img_height, 3), dtype=np.float32)
y_data = np.zeros((num_samples, num_classes), dtype=np.float32)

for i in range(num_samples):
    label_idx = i % num_classes  # Chia đều mẫu cho các hệ
    y_data[i, label_idx] = 1.0

    # Màu da nền mặc định (Hồng cam nhạt)
    base_color = np.array([0.92, 0.78, 0.68])
    img = np.ones((img_width, img_height, 3)) * base_color

    # -----------------------------------------------------------------
    # THIẾT LẬP TIÊU CHUẨN HÌNH HỌC THEO TỪNG LOẠI TAY (Bản chất để CNN học)
    # -----------------------------------------------------------------
    if label_idx == 0:  # HỆ KIM: Tạo khung bàn tay vuông, các nét thẳng thô
        # Vẽ một khối vuông mờ ở giữa đại diện cho lòng bàn tay vuông
        img[20:108, 20:108] -= 0.05
        # Các đường chỉ tay thẳng, vuông góc
        for x in range(30, 90): img[x, 64] = [0.4, 0.3, 0.3]     # Đường dọc thẳng
        for y in range(40, 85): img[64, y] = [0.4, 0.3, 0.3]     # Đường ngang thẳng

    elif label_idx == 1:  # HỆ MỘC: Lòng bàn tay dài, thon, nhiều đường mảnh như gân lá
        img[15:115, 35:95] -= 0.05 # Khung chữ nhật đứng dài
        # Vẽ nhiều đường chỉ tay chéo mảnh, đan xen nhau
        for t in range(20, 100):
            img[t, int(35 + t*0.5)] = [0.5, 0.4, 0.4]
            img[t, int(95 - t*0.4)] = [0.5, 0.4, 0.4]

    elif label_idx == 2:  # HỆ THỦY: Lòng bàn tay tròn, các đường uốn cong mềm mại
        # Dùng thuật toán khoảng cách để vẽ một hình tròn mờ gò bàn tay
        for x in range(img_width):
            for y in range(img_height):
                if (x-64)**2 + (y-64)**2 < 45**2:
                    img[x, y] -= 0.05
        # Vẽ đường chỉ tay cong (đường hình sin mềm mại)
        for x in range(25, 100):
            y = int(64 + 20 * np.sin(x / 15.0))
            if 0 <= y < img_height: img[x, y] = [0.4, 0.3, 0.3]

    elif label_idx == 3:  # HỆ HỎA: Tay nhọn búp măng, các đường hướng tụ lên trên
        # Tạo vùng hình tam giác/hình chóp đại diện cho cấu trúc tay nhọn
        for x in range(20, 110):
            tỷ_lệ_rộng = int((110 - x) * 0.4)
            img[x, 64-tỷ_lệ_rộng : 64+tỷ_lệ_rộng] -= 0.05
        # Các đường chỉ tay chéo cao, hướng xiên lên các ngón tay
        for x in range(40, 100):
            img[x, int(64 + (100-x)*0.5)] = [0.4, 0.3, 0.3]
            img[x, int(64 - (100-x)*0.5)] = [0.4, 0.3, 0.3]

    elif label_idx == 4:  # HỆ THỔ: Bàn tay dày vững chãi, nét chỉ tay rất đậm và sâu
        img[25:105, 25:105] -= 0.08 # Khối thịt dày (độ tương phản cao hơn)
        # Vẽ các nét chỉ tay siêu đậm (độ rộng nét lớn)
        for x in range(30, 95):
            img[x, 45:48] = [0.3, 0.2, 0.2] # Nét dày 3 pixel
            img[x, 80:83] = [0.3, 0.2, 0.2]

    X_data[i] = img

# Trộn ngẫu nhiên dữ liệu sau khi đã gán tiêu chuẩn để máy học khách quan
indices = np.arange(num_samples)
np.random.shuffle(indices)
X_data, y_data = X_data[indices], y_data[indices]

# Chia Train (80%) - Validation (20%)
split_idx = int(num_samples * 0.8)
X_train, X_val = X_data[:split_idx], X_data[split_idx:]
y_train, y_val = y_data[:split_idx], y_data[split_idx:]

# --- TĂNG CƯỜNG DỮ LIỆU ---
train_datagen = ImageDataGenerator(
    rotation_range=15, width_shift_range=0.1, height_shift_range=0.1, fill_mode="nearest"
)
train_generator = train_datagen.flow(X_train, y_train, batch_size=32)

# --- XÂY DỰNG MODEL CNN GỐC CỦA BẠN ---
model = Sequential([
    Conv2D(32, (3,3), activation="relu", input_shape=(img_width, img_height, 3)),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation="relu"),
    MaxPooling2D(2,2),
    Conv2D(128, (3,3), activation="relu"),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(128, activation="relu"),
    Dropout(0.5),
    Dense(num_classes, activation="softmax")
])

model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

# --- HUẤN LUYỆN MÔ HÌNH ---
history = model.fit(train_generator, validation_data=(X_val, y_val), epochs=100)

# --- ĐÁNH GIÁ VÀ VẼ BIỂU ĐỒ ---
plt.figure(figsize=(8, 4))
plt.plot(history.history['accuracy'], label="Train Accuracy (Độ chính xác học)")
plt.plot(history.history['val_accuracy'], label="Val Accuracy (Độ chính xác kiểm thử)")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Quá trình học tập của CNN dựa trên Tiêu chuẩn Nhân trắc học")
plt.legend()
plt.show()

# --- TỪ ĐIỂN TỐ CHẤT NHÂN SỰ ---
TU_DIEN_TO_CHAT = {
    0: {"Hệ": "KIM", "Tố chất": "🎯 QUẢN LÝ ĐIỀU HÀNH: Thực tế, kỷ luật cao, quyết đoán. Hợp vị trí COO, Quản lý dự án."},
    1: {"Hệ": "MỘC", "Tố chất": "💡 SÁNG TẠO & CHIẾN LƯỢC: Tư duy sâu, thích nghiên cứu. Hợp vị trí R&D, Hoạch định."},
    2: {"Hệ": "THỦY", "Tố chất": "🤝 NGOẠI GIAO & HR: Khéo léo, thích nghi nhanh, thấu hiểu. Hợp vị trí Quản trị nhân sự, Sales."},
    3: {"Hệ": "HỎA", "Tố chất": "🔥 TRUYỀN CẢM HƯNG: Đam mê, lôi cuốn đám đông. Hợp vị trí Marketing, Leader đội nhóm."},
    4: {"Hệ": "THỔ", "Tố chất": "🛡️ CHUYÊN GIA ĐÁNG TIN CẬY: Cẩn trọng, nguyên tắc. Hợp vị trí Tài chính, Kế toán, Kiểm toán."}
}

# --- HÀM KIỂM TRA ẢNH MỚI ---
def xem_chi_tay_thuc_te(duong_dan_anh):
    import os
    from tensorflow.keras.preprocessing.image import load_img, img_to_array
    if not os.path.exists(duong_dan_anh):
        print(f"\n[INFO] Thuật toán đã sẵn sàng. Truyền đường dẫn ảnh thật vào hàm để chạy.")
        return
    img = load_img(duong_dan_anh, target_size=(128, 128))
    img_array = img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    du_doan = model.predict(img_array)
    idx = np.argmax(du_doan[0])

    print("="*60)
    print(f"🔮 KẾT QUẢ PHÂN TÍCH TỪ CNN: HỆ {TU_DIEN_TO_CHAT[idx]['Hệ']}")
    print(f"🔹 Định hướng tố chất: {TU_DIEN_TO_CHAT[idx]['Tố chất']}")
    print("="*60)

xem_chi_tay_thuc_te('/content/707078828_997070926201596_457216416089858232_n.jpg')

